name: Deploy Frontend Web App

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_PACKAGE_PATH: './frontend'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            frontend/requirements.txt

      - name: Create requirements.txt for frontend
        run: |
          cd frontend
          echo "streamlit" > requirements.txt
          echo "azure-storage-blob" >> requirements.txt
          echo "pillow" >> requirements.txt
          echo "python-dotenv" >> requirements.txt
          echo "requests" >> requirements.txt

      - name: Create startup command file
        run: |
          cd frontend
          echo "streamlit run app.py --server.port 8000" > startup.sh
          chmod +x startup.sh

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy Frontend Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          startup-command: "sh startup.sh"
